# Copyright (c) 2026
# SPDX-License-Identifier: MIT

# 覆盖/补充 shield conf；板级 UF2 见 README
CONFIG_ZMK_UNIFYING=y
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=32
CONFIG_BT_MAX_PAIRED=3
CONFIG_BT_MAX_CONN=3
