# Copyright (c) 2026
# SPDX-License-Identifier: MIT

# Nordic ESB（来自 west 拉取的 sdk-nrf / nrf 模块）
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=32

CONFIG_ZMK_UNIFYING=y

CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_ENTROPY_GENERATOR=y

CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS=y

# 三路 BLE profile
CONFIG_BT_MAX_PAIRED=3
CONFIG_BT_MAX_CONN=3

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_INF=y
